"""Create Offers table

Revision ID: cab4368f2702
Revises: 
Create Date: 2023-07-04 00:49:35.911807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab4368f2702'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.String(), server_default='gen_random_uuid()', nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('salary_lower_bound', sa.Integer(), nullable=False),
    sa.Column('salary_upper_bound', sa.Integer(), nullable=False),
    sa.Column('skills', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_company_name'), 'offers', ['company_name'], unique=False)
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    op.create_index(op.f('ix_offers_location'), 'offers', ['location'], unique=False)
    op.create_index(op.f('ix_offers_salary_lower_bound'), 'offers', ['salary_lower_bound'], unique=False)
    op.create_index(op.f('ix_offers_salary_upper_bound'), 'offers', ['salary_upper_bound'], unique=False)
    op.create_index(op.f('ix_offers_skills'), 'offers', ['skills'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offers_skills'), table_name='offers')
    op.drop_index(op.f('ix_offers_salary_upper_bound'), table_name='offers')
    op.drop_index(op.f('ix_offers_salary_lower_bound'), table_name='offers')
    op.drop_index(op.f('ix_offers_location'), table_name='offers')
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_company_name'), table_name='offers')
    op.drop_table('offers')
    # ### end Alembic commands ###
